language: rust
cache:
  - npm
  - yarn
  - cargo
before_script:
  - rustup component add rustfmt
script:
  - >
    cargo fmt --all -- --check &&
    cargo build --verbose &&
    cargo test --all -- --nocapture
rust:
  - stable
node_js:
  - node
