[package]
name = "binjs"
version = "0.2.0"
authors = ["David Teller <D.O.Teller@gmail.com>"]

[features]
default = []
# If specified, build support for using SpiderMonkey as a parser.
spidermonkey = []
esprima = []

[dependencies]
assert_matches = "*"
brotli = "1.*"
clap = "*" # Should be a dev-dependency, actually.
env_logger = "*"
flate2 = "0.2"
log = "*"
lzw = "*"
rand = "*"
serde = "*"
serde_json = { path = "../blurbs/serde-json" }

[dev-dependencies]
env_logger = "*"
glob = "*"
test-logger = "*"
